apiVersion: v1
kind: PersistentVolume
metadata:
  name: velora-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/velora
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velora-db-pvc
  namespace: velora
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
